env:
  ARTIFACTORY_SERVER: 'docker.artifactory.internal.amount.com'
steps:
  - agents:
      queue: eks-buildkite-agent
    label: ":docker::python::aws:"
    plugins:
      - docker-compose#v3.7.0:
          run: app
    #command: './test_pipeline/copyFiles.sh'
    command: echo "HELLLOOOOOOOO!"