env:
  ARTIFACTORY_SERVER: 'docker.artifactory.internal.amount.com'
steps:
  - commands: 
      - "chmod +x define_steps.sh"  
      - "./define_steps.sh | buildkite-agent pipeline upload"
    label: ':pipeline: Pipeline Upload'
    agents: 
      queue: eks-buildkite-agent