env:
  ARTIFACTORY_SERVER: 'docker.artifactory.internal.amount.com'
steps:
  - agents:
      queue: eks-buildkite-agent
    label: ":docker::python:"
    plugins:
      - docker-compose#v3.7.0:
          run: app