steps:
  # - label: ":git: Script"
  #   env:
  #     # This value should never change for builds to artifactory
  #     BUILDKITE_ARTIFACT_UPLOAD_DESTINATION: "rt://TFSec"
  #   command:
  #     - pip install GitPython 
  #     - python3 -m pip install GitPython
  #     - python3 TFSec_part1.py
  #   artifact_paths: "reports/*"

  # - label: ":docker: :python:"
  #   command: "python3 TFSec_part1.py"
  #   plugins:
  #     - docker-compose#v3.7.0:
  #         run: app
  - label: ":docker::python:"
    #command: "py.test"
    plugins:
      - docker-compose#v3.7.0:
          run: app
  - wait
  - label: "Generate files and push to S3 :package:"
    plugins:
      - envato/aws-s3-sync#v0.3.0:
          source: Reports/
          destination: s3:/reports-amount-tfsec/2021-09-29/