steps:
  - label: "Example Test"
    command: echo "Hello!"
    #key: pull-request

  - label: ":desktop_computer:"
    command: echo "Here is where is gonna start the script running"
    #depends_on: 
    #- pull-request
  
  - label: "git script"
    command: python3 -m pip install GitPython | python3 TFSec_part1
    #key: pull-request
    