steps:
  - label: ":git: Script"
    env:
      # This value should never change for builds to artifactory
      # BUILDKITE_ARTIFACT_UPLOAD_DESTINATION: "rt://TFSec"
    command:
      - pip install GitPython 
      - python3 -m pip install GitPython
      - pipenv install --deploy --dev
      - pipenv run TFSec_part1.py
      #- python3 TFSec_part1.py
    #artifact_paths: "tfsec-*"