steps:
  - label: ":git: Script"
    env:
      # This value should never change for builds to artifactory
      BUILDKITE_ARTIFACT_UPLOAD_DESTINATION: "rt://TFSec"
    command:
      - pip install GitPython 
      - python3 -m pip install GitPython
      - python3 TFSec_part1.py
      - buildkite-agent artifact upload /var/lib/buildkite-agent/Tools/*
    artifact_paths: "/var/lib/buildkite-agent/Tools/*"

  - name: ":docker: :python:"
    command: "python3 TFSec_part1.py"
    plugins:
      - docker-compose#v3.7.0:
          run: app
